name: BasicServerPlugin
main: basic.Main
version: 0.2-developing
api-version: 1.16
author: bjw300/백조, peanutexe/땅콩
description: this plugin is Basic Utility plugin
website: https://github.com/bjw300/BasicServerPlugin

commands:
  메뉴:
    description: "(gui)server menu"
  상점:
    description: "(gui)server shop"
  관리자메뉴:
    description: "(gui)task menu"
  월드메뉴:
    description: "(gui)world menu"
  설정:
    description: "(gui)setting"
  정보표시창:
    description: "(scoreboard)on/off scoreboard"
  명령어:
    description: "(command)execute help"
  warp:
    description: "(command)save/tp location"
  칭호설정:
    description: "(command)Set the title"
  b:
    description: "(command)plugin utility tool"