name: BasicServerPlugin
main: basic.Main
version: 0.2-developing
api-version: 1.16
author: bjw300/백조, peanutexe/땅콩
description: this plugin is Basic Utility plugin
website: https://github.com/bjw300/BasicServerPlugin

commands:
  메뉴:
    description: "execute server menu"
  상점:
    description: "execute server shop"
  관리자메뉴:
    description: "execute task menu"
  월드메뉴:
    description: "execute world menu"
  설정:
    description: "execute setting"
  정보표시창:
    description: "on/off scoreboard"
  명령어:
    description: "execute help"
  칭호설정:
    description: "Set the title"
  b:
    description: "plugin utility tool"